dist: trusty
sudo: false
language: node_js

matrix:
  include:
    - node_js: "node"
    - node_js: "10"
    - node_js: "9"
      env: NODE_FLAGS=--harmony_promise_finally
    - node_js: "8"
      env: NODE_FLAGS=--harmony_promise_finally

notifications:
  email:
    on_failure: always

branches:
  only:
    - master

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE fixtures_test;'
  - mysql -e 'CREATE TABLE fixtures_test.roles (id INT AUTO_INCREMENT, name VARCHAR(100) NULL, PRIMARY KEY(id));'
  - mysql -e 'CREATE TABLE fixtures_test.users (id INT AUTO_INCREMENT, email VARCHAR(150) NOT NULL, role_id INT NOT NULL, PRIMARY KEY(id), FOREIGN KEY (role_id) REFERENCES fixtures_test.roles(id));'

install:
  - npm install

script:
  - npm run lint
  - npm run build
  - npm test -- test/unit/ $NODE_FLAGS
  - npm test -- test/integration/ $NODE_FLAGS
  - npm test -- test/e2e/ $NODE_FLAGS